### ISSUE TITLE
Character_Copy Table Checklist

### ISSUE THREAD

**Issue by nazwadi** [nazwadi/peqquery#2]
- [x] alternate_currency
- [x] char_recipe_list
- [x] character_activities
- [x] character_alt_currency
- [x] character_alternate_abilities
- [x] character_auras
- [x] character_bandolier
- [x] character_bind
- [x] character_buffs
- [x] character_corpse_items
- [x] character_corpses
- [x] character_currency
- [x] character_data
- [x] character_disciplines
- [x] character_enabledtasks
- [x] character_exp_modifiers
- [x] character_expedition_lockouts
- [x] character_inspect_messages
- [x] character_instance_safereturns
- [x] character_item_recast
- [x] character_languages
- [x] character_leadership_abilities
- [x] character_material
- [x] character_memmed_spells
- [x] character_pet_buffs
- [x] character_pet_info
- [x] character_pet_inventory
- [x] character_potionbelt
- [x] character_skills
- [x] character_spells
- [x] character_task_timers
- [x] character_tasks
- [x] character_tribute
- [x] completed_shared_task_activity_state
- [x] completed_shared_task_members
- [x] completed_shared_tasks
- [x] completed_tasks
- [x] data_buckets
- [x] discovered_items
- [x] dynamic_zone_members
- [x] faction_values
- [x] friends
- [x] group_id
- [x] group_leaders
- [x] guild_bank
- [x] guild_members
- [x] guilds
- [x] instance_list
- [x] instance_list_player
- [x] inventory
- [x] inventory_snapshots
- [x] ip_exemptions
- [x] keyring
- [x] lfguild
- [x] mail
- [x] petitions
- [x] player_titlesets
- [x] quest_globals
- [x] raid_details
- [x] raid_members
- [x] reports
- [x] shared_task_members
- [x] shared_tasks
- [x] sharedbank
- [x] spell_buckets
- [x] spell_globals
- [x] timers
- [x] titles
- [x] trader
- [x] trader_audit
- [x] veteran_reward_templates
- [x] zone_flags

**Comment by nazwadi** [comment]
ORM Models for the character copy tables are complete.  Closing this issue.
